- name: Add DB2 users
  ansible.builtin.include_role:
    name: common
    tasks_from: add-db2-user
  vars:
    common_k8s_api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cp4ba_k8s_host | default(omit) }}"
    common_db2_user: "{{ item }}"
    common_db2_password: "{{ cp4ba_db2_universal_password }}"
  with_items:
    - pb
    - bas

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=studio-creating-databases
- name: PB DB
  kubernetes.core.k8s_exec:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    namespace: db2
    pod: c-db2ucluster-db2u-0
    command: >
      su - db2inst1 -s /usr/bin/bash -c "
      db2 CONNECT TO CP4BA;
      db2 CREATE REGULAR TABLESPACE PB_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE USER TEMPORARY TABLESPACE PB_TEMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE SYSTEM TEMPORARY TABLESPACE PB_SYSTMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;

      db2 GRANT DBADM ON DATABASE TO user pb;
      db2 GRANT USE OF TABLESPACE PB_TS TO user pb;
      db2 GRANT USE OF TABLESPACE PB_TEMP_TS TO user pb;
      db2 CONNECT RESET;
      "
  register: command_status

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=studio-creating-databases
- name: BAS DB
  kubernetes.core.k8s_exec:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    namespace: db2
    pod: c-db2ucluster-db2u-0
    command: >
      su - db2inst1 -s /usr/bin/bash -c "
      db2 CONNECT TO CP4BA;
      db2 CREATE REGULAR TABLESPACE BAS_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE USER TEMPORARY TABLESPACE BAS_TEMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE SYSTEM TEMPORARY TABLESPACE BAS_SYSTMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;

      db2 GRANT DBADM ON DATABASE TO user bas;
      db2 GRANT USE OF TABLESPACE BAS_TS TO user bas;
      db2 GRANT USE OF TABLESPACE BAS_TEMP_TS TO user bas;
      db2 CONNECT RESET;
      "
  register: command_status
