- name: Create & configure CP4BA DB
  kubernetes.core.k8s_exec:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    namespace: db2
    pod: c-db2ucluster-db2u-0
    command: >
      su - db2inst1 -s /usr/bin/bash -c "
      db2 create database CP4BA automatic storage yes using codeset UTF-8 territory US pagesize 32768;
      db2 UPDATE DB CFG FOR CP4BA USING LOGFILSIZ 16384 DEFERRED;
      db2 UPDATE DB CFG FOR CP4BA USING LOGPRIMARY 64 IMMEDIATE;
      db2 UPDATE DB CFG FOR CP4BA USING LOGSECOND 64 IMMEDIATE;
      db2 activate db CP4BA;
      db2 CONNECT TO CP4BA;
      db2 CREATE BUFFERPOOL CP4BA_BP_32K IMMEDIATE SIZE AUTOMATIC PAGESIZE 32K;
      db2 DROP TABLESPACE USERSPACE1;
      "
  register: command_status
  failed_when: command_status.rc != 0 and command_status.stdout is not search('.*The database alias \"CP4BA\" already exists.*')
