- name: Add DB2 users
  ansible.builtin.include_role:
    name: common
    tasks_from: add-db2-user
  vars:
    common_k8s_api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cp4ba_k8s_host | default(omit) }}"
    common_db2_user: odm
    common_db2_password: "{{ cp4ba_db2_universal_password }}"

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=manager-configuring-external-database
- name: ODM DB
  kubernetes.core.k8s_exec:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    namespace: db2
    pod: c-db2ucluster-db2u-0
    command: >
      su - db2inst1 -s /usr/bin/bash -c "
      db2 CONNECT TO CP4BA;
      db2 CREATE REGULAR TABLESPACE ODM_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE USER TEMPORARY TABLESPACE ODM_TEMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE SYSTEM TEMPORARY TABLESPACE ODM_SYSTMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE TABLESPACE RESDWTS PAGESIZE 32K BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE SYSTEM TEMPORARY TABLESPACE RESDWTMPTS PAGESIZE 32K BUFFERPOOL CP4BA_BP_32K;

      db2 GRANT DBADM ON DATABASE TO user odm;
      db2 GRANT USE OF TABLESPACE ODM_TS TO user odm;
      db2 GRANT USE OF TABLESPACE ODM_TEMP_TS TO user odm;
      db2 GRANT USE OF TABLESPACE RESDWTS TO user odm;

      db2 'CREATE TABLE odm.EXECUTION_TRACES (
        ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
        TIME_STAMP BIGINT,
        LOCATION VARCHAR(2000),
        REQUEST_PATH VARCHAR(2000) NOT NULL,
        CANONICAL_PATH VARCHAR(2000) NOT NULL,
        RULESET_PROPERTIES CLOB(1G),
        ELAPSED_TIME BIGINT,
        USER_DATA CLOB(1G),
        NB_RULES INT,
        NB_RULES_FIRED INT,
        NB_RULES_NOT_FIRED INT,
        NB_TASKS INT,
        NB_TASKS_EXECUTED INT,
        NB_TASKS_NOT_EXECUTED INT,
        RULES CLOB(1G),
        TASKS CLOB(1G),
        EXECUTION_TRACE_TREE CLOB(1G),
        EXEC_OUTPUT CLOB(1G),
        INPUT_PARAMS CLOB(1G),
        OUTPUT_PARAMS CLOB(1G),
        EXECUTION_ID VARCHAR(255) NOT NULL,
        FULL_EXECUTION_TRACE CLOB(1G),
        CONSTRAINT ET_PK PRIMARY KEY (ID),
        CONSTRAINT EID_UNQ UNIQUE (EXECUTION_ID)
      ) IN RESDWTS;';
      echo 'This is fixing the shell premature exist - do not remove';
      db2 CONNECT RESET;
      "
  register: command_status
