- name: Remove usage Config Map
  kubernetes.core.k8s:
    api_key: "{{ ocp_cluster_token | default(omit) }}"
    host: "{{ ocp_api_endpoint | default(omit) }}"
    state: absent
    api_version: v1
    kind: ConfigMap
    name: usage
    namespace: apollo-one-shot
    force: false
    wait: true
    wait_sleep: 15
    wait_timeout: 15
