# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=openshift-installing-production-deployments

- name: Repository
  include_tasks: repository.yml
  when: _cp4ba_run_repository

- name: DBs
  include_tasks: dbs.yml
  when: _cp4ba_run_dbs

- name: Predeploy
  include_tasks: predeploy.yml
  when: _cp4ba_run_predeploy

- name: Deploy
  block:

    - name: Deploy
      include_tasks: deploy.yml
      when: _cp4ba_run_deploy

    - name: Set failted state to false
      ansible.builtin.set_fact:
        _cp4ba_run_deploy_failed: false

  rescue:

    - name: Set failed state
      ansible.builtin.set_fact:
        _cp4ba_run_deploy_failed: true

    - name: CR & Log
      include_tasks: cr-log.yml
      when: _cp4ba_run_deploy

    - name: End play
      ansible.builtin.fail:
        msg: CP4BA deployment failed.

- name: Deploy CR & Log
  include_tasks: cr-log.yml
  when: _cp4ba_run_deploy

- name: Postdeploy
  include_tasks: postdeploy.yml
  when: _cp4ba_run_postdeploy
