# Based on https://www.ibm.com/docs/en/cpfs?topic=online-uninstalling-foundational-services

- name: Remove IBM Cloud Pak foundational services Operator
  ansible.builtin.include_role:
    name: common
    tasks_from: remove-operator
  vars:
    common_k8s_api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cpfs_k8s_host | default(omit) }}"
    common_namespace_name: ibm-common-services
    common_label_selector_stub: ibm-common-service-operator

- name: Get OperandRequest CRD
  kubernetes.core.k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: operandrequests.operator.ibm.com
  register: operandrequest_crd
  retries: 10
  delay: 1

- name: Delete all OperanRequests
  block:

    - name: Get all OperandRequest
      kubernetes.core.k8s_info:
        api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
        host: "{{ cpfs_k8s_host | default(omit) }}"
        api_version: operator.ibm.com/v1alpha1
        kind: OperandRequest
        namespace: ibm-common-services
      register: operand_requests
      retries: 10
      delay: 1

    - name: Delete All OperandRequest
      kubernetes.core.k8s:
        api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
        host: "{{ cpfs_k8s_host | default(omit) }}"
        state: absent
        api_version: operator.ibm.com/v1alpha1
        kind: OperandRequest
        name: "{{ item.metadata.name }}"
        namespace: ibm-common-services
      with_items: "{{ operand_requests.resources }}"

    - name: Wait All OperandRequest disappear
      kubernetes.core.k8s_info:
        api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
        host: "{{ cpfs_k8s_host | default(omit) }}"
        api_version: operator.ibm.com/v1alpha1
        kind: OperandRequest
        name: "{{ item.metadata.name }}"
        namespace: ibm-common-services
      with_items: "{{ operand_requests.resources }}"
      register: operand_request
      retries: 40
      delay: 30
      until: operand_request.resources | length == 0

  when: operandrequest_crd.resources | length != 0

- name: Get OperandConfig CRD
  kubernetes.core.k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: operandconfigs.operator.ibm.com
  register: operandconfig_crd
  retries: 10
  delay: 1

- name: Remove OperandConfig common-service
  kubernetes.core.k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: operator.ibm.com/v1alpha1
    kind: OperandConfig
    name: common-service
    namespace: ibm-common-services
  retries: 15
  delay: 2
  when: operandconfig_crd.resources | length != 0

- name: Get OperandRegistry CRD
  kubernetes.core.k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: operandregistries.operator.ibm.com
  register: operandregistry_crd
  retries: 10
  delay: 1

- name: Remove OperandRegistry common-service
  kubernetes.core.k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: operator.ibm.com/v1alpha1
    kind: OperandRegistry
    name: common-service
    namespace: ibm-common-services
  retries: 15
  delay: 2
  when: operandregistry_crd.resources | length != 0

- name: Get NamespaceScope CRD
  kubernetes.core.k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: namespacescopes.operator.ibm.com
  register: namespacescope_crd
  retries: 10
  delay: 1

- name: Delete all NamespaceScope
  block:

    - name: Get all NamespaceScope
      kubernetes.core.k8s_info:
        api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
        host: "{{ cpfs_k8s_host | default(omit) }}"
        api_version: operator.ibm.com/v1
        kind: NamespaceScope
        namespace: ibm-common-services
      register: namespace_scopes
      retries: 10
      delay: 1

    - name: Delete All NamespaceScope
      kubernetes.core.k8s:
        api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
        host: "{{ cpfs_k8s_host | default(omit) }}"
        state: absent
        api_version: operator.ibm.com/v1
        kind: NamespaceScope
        name: "{{ item.metadata.name }}"
        namespace: ibm-common-services
        wait: true
        wait_sleep: 5
        wait_timeout: 180
      with_items: "{{ namespace_scopes.resources }}"

    - name: Get all NamespaceScope cs-control
      kubernetes.core.k8s_info:
        api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
        host: "{{ cpfs_k8s_host | default(omit) }}"
        api_version: operator.ibm.com/v1
        kind: NamespaceScope
        namespace: cs-control
      register: namespace_scopes
      retries: 10
      delay: 1

    - name: Delete All NamespaceScope cs-control
      kubernetes.core.k8s:
        api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
        host: "{{ cpfs_k8s_host | default(omit) }}"
        state: absent
        api_version: operator.ibm.com/v1
        kind: NamespaceScope
        name: "{{ item.metadata.name }}"
        namespace: cs-control
        wait: true
        wait_sleep: 5
        wait_timeout: 180
      with_items: "{{ namespace_scopes.resources }}"

  when: namespacescope_crd.resources | length != 0

- name: Remove Operand Deployment Lifecycle Manager Operator
  ansible.builtin.include_role:
    name: common
    tasks_from: remove-operator
  vars:
    common_k8s_api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cpfs_k8s_host | default(omit) }}"
    common_namespace_name: ibm-common-services
    common_label_selector_stub: ibm-odlm

- name: Remove ibmcloud-cluster-ca-cert Secret
  kubernetes.core.k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: v1
    kind: Secret
    name: ibmcloud-cluster-ca-cert
    namespace: kube-public
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove MutatingWebhookConfigurations
  kubernetes.core.k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name: "{{ item }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 50
  with_items:
    - ibm-common-service-webhook-configuration
    - ibm-operandrequest-webhook-configuration

- name: Remove ibm-cs-ns-mapping-webhook-configuration ValidatingWebhookConfiguration
  kubernetes.core.k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name: ibm-cs-ns-mapping-webhook-configuration
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove services Project
  kubernetes.core.k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: services
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove ibm-common-services-status ConfigMap
  kubernetes.core.k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: v1
    kind: ConfigMap
    name: ibm-common-services-status
    namespace: kube-public
    wait: true
    wait_sleep: 5
    wait_timeout: 50

- name: Remove Catalog Sources
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: v1alpha1
    kind: CatalogSource
    name: "{{ item }}"
    namespace: openshift-marketplace
    wait: true
  with_items:
    - opencloud-operators
    - bts-operator
    - cloud-native-postgresql-catalog

- name: Remove ibm-common-services Project
  kubernetes.core.k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: ibm-common-services
    wait: true
    wait_sleep: 5
    wait_timeout: 90

- name: Remove cs-control Project
  kubernetes.core.k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: cs-control
    wait: true
    wait_sleep: 5
    wait_timeout: 90

- name: Remove common-service-maps
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    api_version: v1
    kind: ConfigMap
    name: common-service-maps
    namespace: kube-public
    wait: true

- name: Get Cluster Monitoring ConfigMap
  kubernetes.core.k8s_info:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    kind: ConfigMap
    name: cluster-monitoring-config
    namespace: openshift-monitoring
  register: configmap
  retries: 10
  delay: 1

- name: Remove Cluster Monitoring ConfigMap
  kubernetes.core.k8s:
    api_key: "{{ cpfs_k8s_api_key | default(omit) }}"
    host: "{{ cpfs_k8s_host | default(omit) }}"
    state: absent
    kind: ConfigMap
    name: cluster-monitoring-config
    namespace: openshift-monitoring
    wait: true
    wait_sleep: 15
    wait_timeout: 60
  when: configmap | json_query('resources[0].data.\"apollo-one-shot\"') | bool
